export const PLUS_SHOE = 'PLUS_SHOE'
export const MINUS_SHOE = 'MINUS_SHOE'
export const BUY_SHOE = 'BUY_SHOE'
export const REMOVE_SHOE = 'REMOVE_SHOE'
export const DETAIL_SHOE = 'DETAIL_SHOE'
export const CONVERT_NAME = 'CONVERT_NAME'